apiVersion: provisioning.herder.io/v1alpha1
kind: ProvisioningRule
metadata:
  name: seed-boot
spec:
  triggers:
    - boot
  deviceSelector: {}
  desired:
    script: "boot.ts"
  priority: 50
  enabled: true
